-- models/sql/dim_customer.sql
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."DIM_CUSTOMER" AS
SELECT
    DIM_CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    REGION,
    CITY,
    SEGMENT,
    CREDIT_LIMIT,
    CURRENCY,
    ACTIVE,
    LOAD_TIMESTAMP
FROM "BDC_CAPSTONE"."STG_CUSTOMERS";

-- models/sql/dim_product.sql
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."DIM_PRODUCT" AS
SELECT
    DIM_PRODUCT_KEY,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BASE_PRICE,
    CURRENCY,
    UNIT_OF_MEASURE,
    ACTIVE,
    LOAD_TIMESTAMP
FROM "BDC_CAPSTONE"."STG_PRODUCTS";
