-- =============================================================
-- models/sql/kpi_revenue_analysis.sql
-- SAP BDC (Datasphere) — KPI Analytical View
-- Revenue Analysis: YTD, Regional, Product, Customer breakdown
-- =============================================================

-- ─── 1. Monthly Revenue Trend ───────────────────────────────
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."KPI_MONTHLY_REVENUE" AS
SELECT
    ORDER_YEAR,
    ORDER_MONTH,
    TO_VARCHAR(ORDER_DATE, 'Mon YYYY') AS MONTH_LABEL,
    SUM(REVENUE)                        AS TOTAL_REVENUE,
    COUNT(DISTINCT ORDER_ID)            AS ORDER_COUNT,
    COUNT(DISTINCT CUSTOMER_ID)         AS ACTIVE_CUSTOMERS,
    AVG(REVENUE)                        AS AVG_ORDER_VALUE,
    SUM(DISCOUNT_AMOUNT)                AS TOTAL_DISCOUNT
FROM "BDC_CAPSTONE"."FACT_SALES"
WHERE REVENUE_ELIGIBLE = TRUE
GROUP BY ORDER_YEAR, ORDER_MONTH, TO_VARCHAR(ORDER_DATE, 'Mon YYYY')
ORDER BY ORDER_YEAR, ORDER_MONTH;


-- ─── 2. Revenue by Region ───────────────────────────────────
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."KPI_REVENUE_BY_REGION" AS
SELECT
    REGION,
    SUM(REVENUE)               AS TOTAL_REVENUE,
    COUNT(DISTINCT ORDER_ID)   AS ORDER_COUNT,
    COUNT(DISTINCT CUSTOMER_ID)AS UNIQUE_CUSTOMERS,
    ROUND(SUM(REVENUE) * 100.0 /
        SUM(SUM(REVENUE)) OVER (), 2) AS REVENUE_SHARE_PCT
FROM "BDC_CAPSTONE"."FACT_SALES"
WHERE REVENUE_ELIGIBLE = TRUE
GROUP BY REGION
ORDER BY TOTAL_REVENUE DESC;


-- ─── 3. Top Products by Revenue ─────────────────────────────
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."KPI_TOP_PRODUCTS" AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.REVENUE)              AS TOTAL_REVENUE,
    SUM(f.QUANTITY)             AS UNITS_SOLD,
    COUNT(DISTINCT f.ORDER_ID)  AS ORDER_COUNT,
    ROUND(SUM(f.REVENUE) / NULLIF(SUM(f.QUANTITY), 0), 2) AS AVG_SELLING_PRICE
FROM "BDC_CAPSTONE"."FACT_SALES" f
JOIN "BDC_CAPSTONE"."DIM_PRODUCT" p ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE f.REVENUE_ELIGIBLE = TRUE
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


-- ─── 4. Top Customers by Revenue ────────────────────────────
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."KPI_TOP_CUSTOMERS" AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.SEGMENT,
    c.REGION,
    SUM(f.REVENUE)              AS TOTAL_REVENUE,
    COUNT(DISTINCT f.ORDER_ID)  AS ORDER_COUNT,
    ROUND(SUM(f.REVENUE) / NULLIF(COUNT(DISTINCT f.ORDER_ID), 0), 2) AS AVG_ORDER_VALUE
FROM "BDC_CAPSTONE"."FACT_SALES" f
JOIN "BDC_CAPSTONE"."DIM_CUSTOMER" c ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE f.REVENUE_ELIGIBLE = TRUE
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.SEGMENT, c.REGION
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


-- ─── 5. Quarter-over-Quarter Growth ─────────────────────────
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."KPI_QOQ_GROWTH" AS
WITH quarterly AS (
    SELECT
        ORDER_YEAR,
        ORDER_QUARTER,
        CONCAT('Q', ORDER_QUARTER, ' ', ORDER_YEAR) AS QUARTER_LABEL,
        SUM(REVENUE) AS QUARTERLY_REVENUE
    FROM "BDC_CAPSTONE"."FACT_SALES"
    WHERE REVENUE_ELIGIBLE = TRUE
    GROUP BY ORDER_YEAR, ORDER_QUARTER
)
SELECT
    QUARTER_LABEL,
    QUARTERLY_REVENUE,
    LAG(QUARTERLY_REVENUE) OVER (ORDER BY ORDER_YEAR, ORDER_QUARTER) AS PREV_QUARTER_REVENUE,
    ROUND(
        (QUARTERLY_REVENUE - LAG(QUARTERLY_REVENUE) OVER (ORDER BY ORDER_YEAR, ORDER_QUARTER))
        / NULLIF(LAG(QUARTERLY_REVENUE) OVER (ORDER BY ORDER_YEAR, ORDER_QUARTER), 0) * 100,
    2) AS QOQ_GROWTH_PCT
FROM quarterly
ORDER BY ORDER_YEAR, ORDER_QUARTER;


-- ─── 6. Order Fulfillment Summary ───────────────────────────
CREATE OR REPLACE VIEW "BDC_CAPSTONE"."KPI_FULFILLMENT" AS
SELECT
    STATUS,
    COUNT(*)                                        AS ORDER_COUNT,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS PERCENTAGE,
    SUM(NET_VALUE)                                  AS GROSS_ORDER_VALUE
FROM "BDC_CAPSTONE"."FACT_SALES"
GROUP BY STATUS
ORDER BY ORDER_COUNT DESC;
